apiVersion: v1
kind: Pod
metadata:
  labels:
    docker: kaniko-example
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.8.1-debug
      env:
        - name: AWS_SDK_LOAD_CONFIG
          value: "true"
      command:
        - /kaniko/docker-credential-ecr-login
        - get
      tty: true
      resources:
        requests:
          memory: "100Mi"
        limits:
          memory: "1024Mi"
      imagePullPolicy: Always
    - name: aws-cli
      image: amazon/aws-cli:2.1.33
      command:
        - cat
      tty: true
      resources:
        requests:
          memory: "100Mi"
        limits:
          memory: "1024Mi"
