{
 "title": "Script Engine Worker",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "input_queue",
    "label": "Input Queue",
    "query": {
     "query": "label_values(rabbitmq_channel_messages_acked_total, queue)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average time in queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(phaedra2_scriptengine_worker_receive_delay_seconds_sum{queue=\"$input_queue\"}[$__rate_interval])) / sum(rate(phaedra2_scriptengine_worker_receive_delay_seconds_count{queue=\"$input_queue\"}[$__rate_interval])) "
    }
   ]
  },
  {
   "title": "Average time in queue",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(phaedra2_scriptengine_worker_receive_delay_seconds_sum{queue=\"$input_queue\"}[$__rate_interval])) / sum(rate(phaedra2_scriptengine_worker_receive_delay_seconds_count{queue=\"$input_queue\"}[$__rate_interval])) "
    }
   ]
  },
  {
   "title": "Max time in queue",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(phaedra2_scriptengine_worker_receive_delay_seconds_max{queue=\"$input_queue\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Average idle time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(phaedra2_scriptengine_worker_idle_time_seconds_sum{queue=\"$input_queue\"}[$__rate_interval]))   by (instance) / sum(rate(phaedra2_scriptengine_worker_idle_time_seconds_count{queue=\"$input_queue\"}[$__rate_interval]))  by (instance)"
    }
   ]
  },
  {
   "title": "Min idle time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(phaedra2_scriptengine_worker_idle_time_min{queue=\"$input_queue\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Average idle time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(phaedra2_scriptengine_worker_idle_time_seconds_sum{queue=\"$input_queue\"}[$__rate_interval])) / sum(rate(phaedra2_scriptengine_worker_idle_time_seconds_count{queue=\"$input_queue\"}[$__rate_interval])) "
    }
   ]
  },
  {
   "title": "Min idle time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(phaedra2_scriptengine_worker_idle_time_min{queue=\"$input_queue\"})"
    }
   ]
  },
  {
   "title": "Messages on input queue",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_unacked{queue=\"$input_queue\"} * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info)",
     "legendFormat": "{{rabbitmq_node}}"
    }
   ]
  },
  {
   "title": "Input Messages",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channel_messages_acked_total{queue=\"$input_queue\"}[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info) by(rabbitmq_node)",
     "legendFormat": "Input messages acknowledged / s"
    },
    {
     "expr": "sum(rate(rabbitmq_queue_messages_published_total{queue=\"$input_queue\"}[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info) by(rabbitmq_node)",
     "legendFormat": "Input messages / s"
    }
   ]
  },
  {
   "title": "Procesed scripts",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(phaedra2_scriptengine_worker_processed_scripts_total{queue=\"$input_queue\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Messages published on output queue / s",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_queue_messages_published_total{queue=\"scriptengine_output_for_CalculationService\"}[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info) by(rabbitmq_node)",
     "legendFormat": "{{rabbitmq_node}}"
    }
   ]
  }
 ]
}