apiVersion: v1
kind: Pod
spec:
  volumes:
    - name: dockerconfig
      secret:
        secretName: oa-sa-jenkins-registry-config
  containers:
   - name: builder
     image: registry.openanalytics.eu/openanalytics/phaedra2-build-container:latest
     tty: true
     imagePullPolicy: Always
     securityContext:
       privileged: true
     volumeMounts:
       - name: dockerconfig
         mountPath: /root/.docker/config.json
         subPath: data
     resources:
       requests:
         memory: "4Gi"
         cpu: "500m"
         ephemeral-storage: "30Gi"
       limits:
         memory: "4Gi"
         cpu: "1"
         ephemeral-storage: "30Gi"
