apiVersion: v1
kind: Pod
metadata:
  name: phaedra2-builder
  labels:
    ci: phaedra2-builder
spec:
  imagePullSecrets:
    - name: registry-robot
  containers:
   - name: builder
     image: registry.openanalytics.eu/openanalytics/phaedra2-build-container:latest
     securityContext:
        privileged: true
     resources:
       requests:
         ephemeral-storage: "30Gi"
         memory: "2Gi"
         cpu: "1.0"
       limits:
         ephemeral-storage: "30Gi"
         memory: "2Gi"
         cpu: "1.0"
