apiVersion: v1
kind: Pod
metadata:
  name: phaedra2-script-engine-worker
  labels:
    ci: phaedra2-script-engine-worker-build
spec:
  containers:
   - name: builder
     image: 196229073436.dkr.ecr.eu-west-1.amazonaws.com/openanalytics/phaedra2-build-container:latest
     securityContext:
        privileged: true
     resources:
       requests:
         memory: "2Gi"
         cpu: "1.0"
       limits:
         memory: "2Gi"
         cpu: "1.0"
