apiVersion: v1
kind: Pod
metadata:
  name: phaedra2-script-engine-worker
  labels:
    ci: phaedra2-script-engine-worker-build
spec:
  containers:
   - name: builder
     image: maven:3-openjdk-11
     command:
     - cat
     tty: true
